global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: dockerhubexporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - dockerhubexporter:9170